version: '3'
services:
    back:
        container_name: back
        restart: always
        build:
            context: ./back
            dockerfile: Dockerfile
        volumes:
            - ./back/src:/app/src
            - ./back/tests:/app/tests
            - ./back/package.json:/app/package.json
            - ./back/knexfile.js:/app/knexfile.js
        ports:
            - "3333:3333"
        links:
            - db
        entrypoint: yarn
        command: start
    front:
        container_name: front
        restart: always
        build:
            context: ./front
            dockerfile: Dockerfile
        volumes:
            - ./front/src:/app/src
            - ./front/public:/app/public
        ports:
            - "3000:3000"
            - "35729:35729"
        entrypoint: yarn
        command: start
    db:
        container_name: database
        restart: always
        image: postgres:12.1
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: qwe123
            POSTGRES_DB: crud
        volumes:
            - ~/dbdata:/var/lib/postgresql/data